//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KazanNeft.WebApi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetPhoto
    {
        public long ID { get; set; }
        public long AssetID { get; set; }
        public byte[] AssetPhoto1 { get; set; }
    
        public virtual Asset Asset { get; set; }
    }
}
